import Head from "next/head";
import React from "react";
import { Navbar } from "../../Navbar";

import styles from './MainLayout.module.scss'

export const MainLayout = ({ children }: { children: React.ReactNode }) => (
    <div className={styles.container}>
        <Head>
            <title>Home - Gastón</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <main className={styles.main}>{children}</main>
    </div>
);